spring:
  application:
    name: sysgateway

  cloud:
    gateway:

      globalcors: # 处理跨域请求
        cors-configurations:
          '[/**]':  # 匹配所有请求
            allowedOrigins: "*" # 跨域处理，允许所有的域
            allowedMethods: # 支持的方法
            - GET
            - POST
            - PUT
            - DELETE

      routes:
        - id: myjwt
          uri: lb://myhwt
          predicates:
            - Path=/myjwt/**
          filters:
            - StripPrefix= 1


server:
  port: 9101

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true